### ISSUE TITLE
I am unable to run the code successfully.

### ISSUE THREAD

**Issue by porsachi** [nourhanb/BiasPruner#1]
I am unable to locate the required files such as attributes, functions, and others in the main.py file. How can I find them?

**Comment by jfayyad** [comment]
Hello! Thank you for your input. Those files are updated and included

**Comment by porsachi** [comment]
I’m sorry to bother you again, but I’m still having some issues when running the code.From trainer import train_model, finetune_model，there is not finetune_model in trainer.py. And there are also no ‘my_fairlearn’ and ‘param’ files. Could you please update the usable version?

**Comment by jfayyad** [comment]
Not at all. All missing file were added.
